### PR TITLE
Fix 325

### PR DESCRIPTION
**Pull request by gg9192**

### CODE REVIEW

**Comment by gg9192** [comment]
This gives users a larger quota when their promoted and takes it away if the user is demoted.

**Review by astump — COMMENTED** [review]
I appreciate the idea of lowering the quota if a user is demoted from being leader, but actually, this would not be helpful, as many times users who are leaders for a while are still responsible for data like from large jobs.  So we should just automatically increase quota on promotion, but we should not lower the quota on demotion. Think of former leaders as retired emperors...

**Comment by gg9192** [comment]
That should be easy. PR for you sometime tomorrow.

-Alex Guo

**Comment by gg9192** [comment]
Done with change

**Pull request merged**
