### PR TITLE
Add description for queues

### PR DESCRIPTION
**Pull request by gg9192**
This patch adds the ability for users to be able to add descriptions for their queues.

### CODE REVIEW

**Comment by gg9192** [comment]
You must add a description col. to the queues table. Otherwise, this will not work on prod.

**Comment by astump** [comment]
Hi, Alex.  I believe our build system was set up (by Pat Hawks, a former developer on the project) to allow us to specify schema changes to be applied on deployment.  Could you please look into that, so that this PR will have everything needed to add the change?  As it stands right now, one has to perform this extra step of updating the db before this code will work.  But it should be possible to add a schema change file to the PR, and then it will work without an extra step.  But I am not sure how Pat set this up to work...

**Comment by gg9192** [comment]
I think I know where it is.
I'm at the eye doctor. I'll give you another update by tonight

**Comment by gg9192** [comment]
I have found it, to do the schema change, you need to do ant update-sql

**Comment by gg9192** [comment]
I have implemented the changes that you have requested. Currently, we have a folder with all the schema changes. If you run   ant update-sql, all the database stuff is updated automagically

**Pull request merged**
